stages:
  - build
  - test

black:
  stage: build
  image: python:3.6
  before_script:
    - pip install black
  script:
    - black --check . --diff

pytest:
  stage: test
  image: python:3.6
  before_script:
    - pip install -r requirements-test.txt
  script:
    - pytest